//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G5_Practica3.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonos
    {
        public int ID_Abono { get; set; }
        public int ID_Compra { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Principal Principal { get; set; }
    }
}
